import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Typography } from "../library";
import Section from "../library/Section/Section";
import styles from "../styles/Home.module.css";

//

const Home: NextPage = () => {
  const [title, setTitle] = useState("Initial Title");
  // State
  // State has changed -> React will rerender the component.
  const changeTitle = ({ target }) => {
    // console.log("Event", target.value);
    setTitle(target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography text="Home Page" />
      <button onClick={changeTitle}>Change Title</button>
      <input type="text" onChange={changeTitle} />
      <Section title={title}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur
        optio architecto, placeat blanditiis unde suscipit vero maxime deleniti
        numquam possimus veniam iusto voluptate voluptatem reprehenderit ab!
        Nostrum error itaque obcaecati. Aliquid pariatur optio ullam sapiente
        vitae a deleniti laboriosam, enim velit nam quos blanditiis similique
        voluptas harum animi facere eius nulla recusandae. Repellendus illum
        libero aliquam voluptate provident minima ipsam?
      </Section>
    </div>
  );
};

export default Home;
